### ISSUE TITLE
coverage reporting is missing

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-net#1]
Let's add coverage reporting, as it's done for example in `eo-files` repo. Check the `codecov.yml` file they have in GitHub Actions. Also, don't forget to add the badge to README.

**Comment by kerelape** [comment]
@yegor256 Codecov fails with `not_found`, I can't fix it

**Comment by yegor256** [comment]
@kerelape this will go away. On the next build, it will succeed. Try it.

**Comment by yegor256** [comment]
@kerelape btw, I suggest to have `mvn.yml` and `codecov.yml` actions in the project. Just like we have in eo-files, for example
